// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5628463TrZejmw_WuLq32G2w5y3N1oBk',
    appId: '1:886287501787:web:af2eb2b25d924edb443ffe',
    messagingSenderId: '886287501787',
    projectId: 'flutter-latabernadelgoblin',
    authDomain: 'flutter-latabernadelgoblin.firebaseapp.com',
    storageBucket: 'flutter-latabernadelgoblin.appspot.com',
    measurementId: 'G-6NKCDFHVXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhvH8H6KfoIBAbU69KeZkbE1N60TCDqLk',
    appId: '1:886287501787:android:9e3d05d37c6fe8f5443ffe',
    messagingSenderId: '886287501787',
    projectId: 'flutter-latabernadelgoblin',
    storageBucket: 'flutter-latabernadelgoblin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAJdt0MOM1VCzUzHDJ3-EkgPQ1gAogRh8',
    appId: '1:886287501787:ios:360cf3e44fc3a378443ffe',
    messagingSenderId: '886287501787',
    projectId: 'flutter-latabernadelgoblin',
    storageBucket: 'flutter-latabernadelgoblin.appspot.com',
    iosClientId: '886287501787-1u1nje08dd7bagte7uvouo2tefgndh9c.apps.googleusercontent.com',
    iosBundleId: 'com.ruben.latabernadelgoblin',
  );
}
